name: Add SSH Key
on:
  push:
    branches: [add-ssh-key]
jobs:
  add-key:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Add SSH public key
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEUBSL3Zzf950gN/ZO7oEm8L/h9diwu5Ujtv1PsX4LP6 anareiki-deploy' >> ~/.ssh/authorized_keys
